# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Store.create(name: "Flair Brides + Maids", yelp_id: "flair-brides-maids-boston")
Store.create(name: "Sabella Couture", yelp_id: "sabella-couture-boston")
Store.create(name: "Allegria Bridal", yelp_id: "allegria-bridal-belmont")
Store.create(name: "Precious Memories Bridal", yelp_id: "precious-memories-bridal-malden")
Store.create(name: "Camilla's Bridal", yelp_id: "camillas-bridal-arlington")
Store.create(name: "Vows Bridal Outlet", yelp_id: "vows-bridal-outlet-watertown")
Store.create(name: "Filene's Basement Running of the Brides", yelp_id: "filenes-basement-running-of-the-brides-boston")
Store.create(name: "Country Weddings", yelp_id: "country-weddings-hingham")
Store.create(name: "The Bridal Secret", yelp_id: "the-bridal-secret-quincy")
Store.create(name: "Manhattan Bridals", yelp_id: "manhattan-bridals-dedham")
Store.create(name: "Luke Aaron", yelp_id: "luke-aaron-boston")
Store.create(name: "Clothes Works", yelp_id: "clothes-works-chelsea")
Store.create(name: "Alfred Angelo Bridal", yelp_id: "alfred-angelo-bridal-dedham")
Store.create(name: "Brocades", yelp_id: "brocades-brookline")
Store.create(name: "Grandasia Bridal & Fashion", yelp_id: "grandasia-bridal-and-fashion-quincy")
Store.create(name: "Rossy's Fashions & Bridal", yelp_id: "rossys-fashions-and-bridal-revere")
Store.create(name: "L'elite Bridal Boutique", yelp_id: "l-elite-bridal-boutique-boston")
Store.create(name: "Bride's Choice", yelp_id: "brides-choice-waltham")
Store.create(name: "Chhabra Bridal Wear", yelp_id: "chhabra-bridal-wear-cambridge")
Store.create(name: "Emilia Creations", yelp_id: "emilia-creations-lexington")
Store.create(name: "La Sposa Bridal", yelp_id: "la-sposa-bridal-newton")
Store.create(name: "La Reine Bridal", yelp_id: "la-reine-bridal-waltham")
Store.create(name: "Casa Fiesta & Bridal Shop", yelp_id: "casa-fiesta-and-bridal-shop-lynn")
Store.create(name: "Ana Hernandez", yelp_id: "ana-hernandez-boston")
Store.create(name: "Musette Bridal", yelp_id: "musette-bridal-boston")
Store.create(name: "New Look Bridal", yelp_id: "new-look-bridal-watertown")
Store.create(name: "Vera Wang Boston", yelp_id: "vera-wang-boston-boston")
Store.create(name: "Bride 'n' Belle Boutique", yelp_id: "bride-n-belle-boutique-medford")
Store.create(name: "David's Bridal Dedham", yelp_id: "davids-bridal-dedham-2")
Store.create(name: "David's Bridal Natick", yelp_id: "davids-bridal-natick")
Store.create(name: "David's Bridal Danvers", yelp_id: "davids-bridal-danvers")
Store.create(name: "Ceremony Boston", yelp_id: "ceremony-boston-boston")
Store.create(name: "La Scala Bridal Shoppe", yelp_id: "la-scala-bridal-shoppe-revere")
Store.create(name: "Firas Yousif Originals Bridal & Evening Wear", yelp_id: "firas-yousif-originals-bridal-and-evening-wear-boston")
Store.create(name: "Sonia's Bridal and Quinceañera", yelp_id: "sonias-bridal-and-quinceañera-jamaica-plain")
Store.create(name: "Daniel Faucher Couture Design", yelp_id: "daniel-faucher-couture-design-boston")
Store.create(name: "Ananya Designs", yelp_id: "ananya-designs-arlington")

